### ISSUE TITLE
Anti-raid works on a bot basis, not guild

### ISSUE THREAD

**Issue by develogix** [Kirbi-bot/Kirbi#13]
Channel names can change where channel ids do not

**Comment by naterchrdsn** [comment]
we need to actually make sure this functionality works with the server that is being raided. the message should not be broadcast to other servers.

lets turn this into a research ticket and close it

**Comment by develogix** [comment]
@KnightVision90, the anti-raid channel has been replaced with the default channel for the guild. We need to evaluate guild member adds for each unique guild, not the entire bot.
