### ISSUE TITLE
Add unit tests for bot functionality

### ISSUE THREAD

**Issue by naterchrdsn** [Kirbi-bot/Kirbi#14]
We won't be able to test external apis, nor should we... But we can mock example responses from them so we can test that our bit can handle things thrown at it

**Comment by naterchrdsn** [comment]
all commands with api dependencies should be tested for successful and unsuccessful responses.

**Comment by develogix** [comment]
Linking #28

**Comment by naterchrdsn** [comment]
closing this. this would take a major refactor and would still leave out core functionality.
