### ISSUE TITLE
refactor command handling

### ISSUE THREAD

**Issue by naterchrdsn** [Kirbi-bot/Kirbi#28]
In order to unit test the commands, we would need to ```return``` something from the ```command.process``` function.

This brings back up the discussion of refactoring how commands are handled.
Right now, we could simply return the content of what should be used inside of the msg.channel.send() and that would be easy enough.

thoughts @develogix @Wrunt @KnightVision90

**Comment by develogix** [comment]
There are certain things that will not work with this: prune and all of the music player functionality command.

There are other things that send multiple messages that might make this a bit of a headache (welcome command).

**Comment by naterchrdsn** [comment]
one thought would be to have 2 possible returns:
- send message(s)
- send command (this would allow for scaling for when we add extra administrative commands)

for handling multiple messages, we just send an array and iterate through them.
we would need to add another method to the main class to handle the plugin return logic

**Comment by develogix** [comment]
Linking #14

**Comment by naterchrdsn** [comment]
closing this. we are good for now
