### ISSUE TITLE
Store antiraid settings

### ISSUE THREAD

**Issue by Morandustries** [Kirbi-bot/Kirbi#47]
We need to store the antiraid settings in a json file rather than storing it on the greybot variable so that the settings aren't lost on restart.

**Comment by develogix** [comment]
Need to also probably check for admin rights for use of this command

**Comment by Morandustries** [comment]
Instead of working with json files, were going to want to get a database set up to store settings like these.

This will be on hold until #97 is completed.

**Comment by naterchrdsn** [comment]
completed with #97
