### ISSUE TITLE
Moderation commands need to correctly check for specific permission and fallback to admin

### ISSUE THREAD

**Issue by naterchrdsn** [Kirbi-bot/Kirbi#65]

**Comment by naterchrdsn** [comment]
I was unable to prune in the main server without adding manage messages perm for pruning

**Comment by develogix** [comment]
I'm not sure that this is a bug. The prune command looks to see if the user has the ability to delete messages (all admins have the delete message permission) and if they do it will delete the message count they supply.

I will look into this and at a minimum make the bot respond with a message if it does not have permission to delete messages.

**Comment by develogix** [comment]
This is functioning as designed. You must have the `MANAGE_MESSAGES` permission to delete other users' messages, so the bot checks if you have it; I have added a fail safe where the bot checks if it has the permission as well.
