### ISSUE TITLE
When replying to the !help command, only show commands that that user can use

### ISSUE THREAD

**Issue by develogix** [Kirbi-bot/Kirbi#72]
We have some commands that require permissions to use, yet they show up as available commands to all users who type in !help.

We should probably modify the way the permissions file is read so that it can include this safeguard.

**Comment by naterchrdsn** [comment]
this needs to be expanded slightly, possibly with another ticket.

ideally, on init, the bot would check what commands are available per api and check what commands are available globally (such as the difference with our general plugins, vs something api-specific like admin commands for discord).

then when commands are listed out with !help, the bot would reply to that person with all the available commands on that server/api, and what they have access to with their permission level as well.

**Comment by naterchrdsn** [comment]
replaced by Richardson-Media-House/kirbi-discord#25
