### ISSUE TITLE
Add a database for tracking server settings

### ISSUE THREAD

**Issue by Morandustries** [Kirbi-bot/Kirbi#97]
Currently we are using json files to store server configurations but to ensure scalability we should incorporate a database that we can use to store these settings in, even if its just using something like mongoose and mongodb. This way we can have custom settings stored efficiently and don't have to worry about file manipulation.

**Comment by naterchrdsn** [comment]
Mongodb sounds great

**Comment by naterchrdsn** [comment]
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.html
